CREATE TABLE PROFILE (
    STUDENTID VARCHAR(20) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PROGRAMME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    HOBBIES VARCHAR(255) NOT NULL,
    INTRODUCTION VARCHAR(500) NOT NULL
);
